name: "Publish"

on:
  # release:
  #   types: [published]
  # push:
  #   branches:
  #     - master
  #     - main
  # pull_request:
  #   branches:
  #     - master
  #     - main
  workflow_dispatch:   # manuális indítás

jobs:
  publish:
    name: Publish builder (${{ matrix.arch }}/${{ matrix.abi }})
    permissions:
      packages: write
      contents: read
    if: github.repository_owner == 'villgzs'
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        abi: ["cp314"]
        tag: ["musllinux_1_2"]
        # 32 bites architektúrák
        # arch: ["armv7", "i386"]
        arch: ["armv7"]
        include:
          # Python / Alpine base image
          - abi: cp314
            base: 3.14-alpine3.24

          # armv7 (32-bit ARM)
          - arch: armv7
            platform: linux/arm/v7
            runs-on: ubuntu-24.04   # QEMU-val emulálva

          # i386 (32-bit x86)
          # - arch: i386
          #   platform: linux/386
          #   runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate image name and version
        id: info
        shell: bash
        run: |
          # Saját registry / image név
          # Cseréld a saját username-edre / org-odra!
          name="ghcr.io/${{ github.repository_owner }}/wheels32bit/${{ matrix.arch }}/${{ matrix.tag }}/${{ matrix.abi }}"

          version=$(echo "${{ github.ref }}" | awk -F"/" '{print $NF}')
          if [[ "${version}" == "master" || "${version}" == "main" ]]; then
            version=dev
          fi

          echo "name=$name" >> $GITHUB_OUTPUT
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          # A wheels32bit repo gyökerében lévő Dockerfile-t használja
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          platforms: ${{ matrix.platform }}
          cache-from: type=registry,ref=${{ steps.info.outputs.name }}:dev
          cache-to: type=inline
          build-args: |
            BUILD_FROM=dockergzs/base-python:3.14-alpine3.24-armv7
            # BUILD_FROM=ghcr.io/${{ github.repository_owner }}/base-python:3.14-alpine3.24-${{ matrix.arch }}
            BUILD_ARCH=${{ matrix.arch }}
            CPYTHON_ABI=${{ matrix.abi }}
          tags: |
            ${{ steps.info.outputs.name }}:${{ steps.info.outputs.version }}
            ${{ steps.info.outputs.name }}:${{ github.sha }}
